const MONGO_URL = process.env.MONGO_URL;
const NEXT_PUBLIC_DOMAIN = process.env.NEXT_PUBLIC_DOMAIN;
const NEXT_PUBLIC_API_DOMAIN = process.env.NEXT_PUBLIC_API_DOMAIN;
const GOOGLE_CLIENT_ID = process.env.GOOGLE_CLIENT_ID;
const GOOGLE_CLIENT_SECRET_KEY = process.env.GOOGLE_CLIENT_SECRET_KEY;

export {
  MONGO_URL,
  NEXT_PUBLIC_DOMAIN,
  NEXT_PUBLIC_API_DOMAIN,
  GOOGLE_CLIENT_ID,
  GOOGLE_CLIENT_SECRET_KEY,
};
